[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.0.1"
description = "{{ cookiecutter.project_description }}"
authors = [
  { name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"
dependencies = [
]

[project.optional-dependencies]
# up-to-date dependencies as of 5/24/2023
dev = [
  "pytest==7.3.1",
  "black==23.3.0",
  "isort==5.12.0",
  "mypy==1.3.0",
  "ruff==0.0.269",
]

[project.urls]
"Homepage" = "{{ cookiecutter.homepage_url}}"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
line_length = 120
py_version = 311